### ISSUE TITLE
Fill form with utf8 data fails

### ISSUE THREAD

**Issue by quique0194** [niklasb/webkit-server#27]
I have a PR ready for this, but I need permission

**Comment by niklasb** [comment]
What do you mean, you need permission?

**Comment by quique0194** [comment]
Yep I need permission to push a branch and create a PR

2016-10-18 3:32 GMT-05:00 Niklas Baumstark <notifications@github.com>:

**Comment by niklasb** [comment]
What you can do is fork the repo and push to your own fork, then PR from
there

**Comment by quique0194** [comment]
The error I was getting:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ubuntu/apurata/app/scripts/fetch_sbs_data.py", line 85, in fetch_sbs_data
    ret, html = get_data_from_sbs(data, proxy=proxy, tries=10)
  File "/home/ubuntu/apurata/app/lib/sbs.py", line 140, in get_data_from_sbs
    html_text = get_sbs_html(data, tries, proxy=proxy)
  File "/home/ubuntu/apurata/app/lib/sbs.py", line 56, in get_sbs_html
    ).set(data["last_name_m"].encode('utf-8'))
  File "/usr/local/lib/python2.7/dist-packages/webkit_server.py", line 93, in set
    self._invoke("set", value)
  File "/usr/local/lib/python2.7/dist-packages/webkit_server.py", line 207, in _invoke
    return self.client.issue_node_cmd(cmd, "false", self.node_id, *args)
  File "/usr/local/lib/python2.7/dist-packages/webkit_server.py", line 377, in issue_node_cmd
    return self.conn.issue_command("Node", *args)
  File "/usr/local/lib/python2.7/dist-packages/webkit_server.py", line 518, in issue_command
    self._sock.sendall(arg.encode("utf-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)
```
